[package]
name = "rust"
version = "0.1.0"
authors = ["hcchae <hc.chae@sk.com>"]
edition = "2018"


[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rust"
crate-type = ["cdylib"]
